# Use an official CUDA image as a parent image
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    python3-pip \
    git \
    ffmpeg -y \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

COPY requirements_asr.txt /app/requirements.txt

# Install Whisper dependencies
# RUN pip3 install --upgrade pip
# RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu114

# Clone Whisper repository
# RUN git clone https://github.com/openai/whisper.git /opt/whisper

# Install Whisper
# WORKDIR /opt/whisper
# RUN pip3 install -e .

# Copy gunicorn_starter script
COPY gunicorn_starter.sh /workspace/gunicorn_starter.sh
RUN chmod +x /workspace/gunicorn_starter.sh

# Copy app script
COPY app.py /app/app.py

# Expose the port Whisper will run on
EXPOSE 8003

# Define the gunicorn_starter
ENTRYPOINT ["/workspace/gunicorn_starter.sh"]
