# Use a base image with specific CUDA version installed
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

RUN if [ ! -d /app/setup/models ]; then \
    mkdir -p /app/setup/models && \
    curl -L https://ollama.com/download/ollama-linux-amd64 -o /app/setup/ollama && \
    chmod +x /app/setup/ollama; \
    fi

EXPOSE 11434

ENV OLLAMA_HOST 0.0.0.0
# ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# ENV LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV NVIDIA_VISIBLE_DEVICES=all
ENV OLLAMA_MAX_VRAM=6000
ENV OLLAMA_MODELS=/app/setup/models
ENV OLLAMA_PORT=11434

ENTRYPOINT ["/app/setup/ollama"]
CMD ["serve"]

